[doc] fix buggy move-cli on tutorial
move-language/move pull request #172
Opened 2022-05-30 19:27 UTC by djy0

trying to fix #161 and #171

## Motivation

fix bug on tutorial

### Have you read the [Contributing Guidelines on pull requests](https://github.com/move-language/move/blob/main/CONTRIBUTING.md#developer-workflow)?

yes

## Test Plan

work through the tutorial after doc change

2022-06-01 02:33 UTC, wrwg commented
There was parallel work on the tutorial in #175 which has landed. Sorry for not paying attention to this PR earlier. Could  you rebase and integrate your changes?

2022-06-01 02:49 UTC, djy0 commented
> There was parallel work on the tutorial in #175 which has landed. Sorry for not paying attention to this PR earlier. Could  you rebase and integrate your changes?

never mind, I would rebase and continue the work

2022-06-24 16:30 UTC, sblackshear requested changes
LGTM except for the one bad correction

2022-06-24 16:30 UTC, sblackshear commented on language/documentation/tutorial/step_8_sol/BasicCoin/sources/BasicCoin.move
> +        assert!(!exists<Balance<CoinType>>(Signer::address_of(account)), Errors::already_published(EALREADY_HAS_BALANCE));
```suggestion
        assert!(!exists<Balance<CoinType>>(signer::address_of(account)), errors::already_published(EALREADY_HAS_BALANCE));
```

2022-06-25 13:30 UTC, jiangying000 commented on language/documentation/tutorial/step_8_sol/BasicCoin/sources/BasicCoin.move
> +        assert!(!exists<Balance<CoinType>>(Signer::address_of(account)), Errors::already_published(EALREADY_HAS_BALANCE));
fixed, thank you

2022-06-25 20:34 UTC, sblackshear approved these changes

2022-06-25 20:34 UTC, merged