support windows \r encoding
move-language/move pull request #18
Opened 2022-04-14 00:09 UTC by LemonHX

support windows benchmarking

## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/diem/diem/blob/main/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/diem/diem/tree/main/developers.diem.com, and link to your PR here.)

## If targeting a release branch, please fill the below out as well

 * Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
 * Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
 * Why we must have it for V1 launch.
 * What workarounds and alternative we have if we do not push the PR.

2022-04-14 00:10 UTC, LemonHX commented
@wrwg transfered

2022-04-14 01:20 UTC, tnowacki requested changes

2022-04-14 01:20 UTC, tnowacki commented on language/move-command-line-common/src/character_sets.rs
> +    x == 0x0A || x == 0x0D
Thanks for the PR! And sorry you are having issues, but we won't be able to change this right away.
This restriction was made in response to a potential security vulnerability where comments in Move code commented out the following line, without the programmer knowing. 

We had discussed relaxing this late last year, but did not make any firm plans. We could file an issue and will need to discuss this further

2022-04-14 19:59 UTC, tnowacki commented
After discussing it, we will look at a PR for unicode characters in comments, but will not be accepting anything at this time that allows `\r`, sorry

2022-04-14 20:04 UTC, wrwg commented
Just curious: if only the specific Windows sequence \r\n would be accepted, but not a standalone \r, wouldn't that solve the security problem? It appears pretty restrictive to not allow Move on native Windows.

2022-04-14 22:27 UTC, sblackshear commented
T

> Just curious: if only the specific Windows sequence \r\n would be accepted, but not a standalone \r, wouldn't that solve the security problem? It appears pretty restrictive to not allow Move on native Windows.

That solution sounds reasonable to me, but I don't have the right context on the parser to understand how easy it is to do this.

@LemonHX : would you mind de-scoping this PR to the parser change only (i.e., move the benchmarking code to a separate PR?)

2022-04-15 03:06 UTC, LemonHX commented
@sblackshear I will do that

2022-04-15 03:07 UTC, LemonHX commented
@wrwg so we could add to our documentation that if you are windows user please config your git before generating any move file

2022-04-15 03:08 UTC, LemonHX commented
@wrwg \r is used in native mac...

2022-04-15 03:17 UTC, wrwg commented
> @wrwg \r is used in native mac...

... and we will not allow it if it is used. We only allow regular ascii files, where lines can be separated either with \n (mac) or \r\n (windows). I think this is very easy to add to the lexer.

2022-05-13 17:38 UTC, wrwg commented
Superseded by #90

2022-05-13 17:38 UTC, closed without merging