Fix/handle multi root workspaces in ide
move-language/move pull request #185
Opened 2022-06-06 18:04 UTC by zjhmale

## Motivation

Fixes https://github.com/MystenLabs/sui/issues/2234

## Test Plan

2022-06-08 15:22 UTC, awelc requested changes
Generally, it looks like a step in the right direction, namely to introduce a global mapping to store symbolication information for all workspaces, but at this point it does not work for me. I checked out the code from the branch, build the language server, and the go-to-def request hangs when executed from the second workspace loaded. I am attaching a short clip showing the problem. My apologies for poor quality of the clip, but GitHub does not allow attachments larger than 10MB - I simply opened sui/sui_programmability/tutorial and than added another folder to the workspace (sui/sui_programmability/examples/nfts).

https://user-images.githubusercontent.com/1724397/172653985-efc7bd2f-9eac-44d5-aa45-a6f9ff14b114.mov

2022-06-10 12:45 UTC, zjhmale commented
@awelc thx for reviewing! still checking the issue mentioned with ur clip

2022-06-10 14:24 UTC, zjhmale commented on language/move-analyzer/src/bin/move-analyzer.rs
> -            symbolicator_runner.run();
sure, will check that later

2022-06-21 07:24 UTC, awelc commented
Any progress on this? I think we will need this piece for the more official release of the new version of the extension...

2022-06-28 00:28 UTC, awelc commented
My apologies but wee had to accelerate development of this feature and it now implemented in #220 which implies closing this one.

2022-06-28 00:28 UTC, closed without merging