feat(stdlib): encode and decode base16
move-language/move pull request #408
Opened 2022-08-24 07:54 UTC by zouguangxian

## Motivation

provide a human-friendly representation of binary-coded values.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/move-language/move/blob/main/CONTRIBUTING.md#developer-workflow)?

Yes

## Test Plan

`move test` passed in language/move-stdlib/nursery/sources directory.

2022-09-03 15:28 UTC, sblackshear commented
I am personally in favor of having more of these utility encoding/decoding libraries inside the Move stdlib, but we need to think carefully about how we want to organize them--one module per format (as this suggests?). All in one big `bytes` module? Something else?

2022-09-06 01:44 UTC, jolestar commented
I support `one module per format`

2022-10-03 16:30 UTC, sblackshear requested changes
This looks good to me at a high level, and I would like to see it go in. But this needs a lot more tests for both the expected behavior and the abort cases.

2022-10-03 16:31 UTC, sblackshear commented
Another approach we could consider here (that would make the testing burden a bit less onerous) is to implement this via `native` functions that wrap the Rust `hex` library.

2022-10-04 06:40 UTC, jolestar commented
> Another approach we could consider here (that would make the testing burden a bit less onerous) is to implement this via `native` functions that wrap the Rust `hex` library.

I also think it is possible to let the User Module implement a native function with a WASM runtime in the future. This approach lets adding new native functions more gracefully and does not need a hard fork upgrade.

2026-02-07 14:00 UTC, closed without merging