[move-package] Update cached git packages to latest state automatically
move-language/move pull request #471
Opened 2022-09-10 20:28 UTC by gregnazario

## Motivation

Currently, the cached packages are never updated, even though they check out the corresponding git repo.  This will now just fetch and reset accordingly to update the local cached version.  Note, this will require a network connection for whenever the compiler is run with a git dependency (though, normally you need it if you don't have it cached).

https://github.com/move-language/move/issues/468

### Have you read the [Contributing Guidelines on pull requests](https://github.com/move-language/move/blob/main/CONTRIBUTING.md#developer-workflow)?

Yes

## Test Plan

TBD, I need to test it with the Move CLI

2022-09-11 06:51 UTC, gregnazario commented
There is a risk here that it changes the behavior.  You can't use a git repo to build Move while not connected to the internet e.g. on a plane.

I'd like to know the opinions accordingly

2022-09-11 19:28 UTC, sblackshear commented
> There is a risk here that it changes the behavior. You can't use a git repo to build Move while not connected to the internet e.g. on a plane.
> 
> I'd like to know the opinions accordingly

Good point! Couple of ideas on this:
- I think it would make sense to add a `-no-git-dep-updates` (or similar) CLI flag + suggest using this flag in the appropriate error message. This would allow you to keep building (but possibly without the latest git deps) if you don't have a network connection.
- See inline comment for making the fetch lazier--this should (hopefully) reduce the frequency of hitting the "can't build without a network connection" issue

2022-09-11 19:28 UTC, sblackshear commented on language/tools/move-package/src/resolution/resolution_graph.rs
> +            } else {
I think we can make this a bit lazier--if `git_rev` is a hash instead of a branch, updates aren't possible and we can skip the fetch.

2022-09-11 19:28 UTC, sblackshear commented on language/tools/move-package/src/resolution/resolution_graph.rs
> +                // NOTE: this means that you must run the package system with a working network connection
Might be helpful to make a note of this in the error message for the `git fetch` command

2022-09-11 19:33 UTC, sblackshear commented
On a more long-term note (no changes suggested for this PR), I am a bit worried about allowing Move programmers to use deps that can skeakily change under their feet by default--seems like a good way to accidentally introduce breaking changes in the benign case, or malicious updates in the worst case. I think it's important to support auto-updateable deps in some form, but we should think carefully about the safest/most convenient way to do this.

One idea might be relying less on the global (and somewhat magical) Move build cache for dependency management and push for something more like `cargo vendor` https://doc.rust-lang.org/cargo/commands/cargo-vendor.html as the default. Will add this topic to the agenda for the next core contributor's meeting, in any case.

2022-09-12 15:14 UTC, sblackshear requested changes
Upon further reflection: instead
- adding an option to skip fetching the latest git deps
- failing with an error message that tells the user to re-run with this option when they are offline

, perhaps we could just use a crate like https://crates.io/crates/online/1.0.0 to check for a network connection and silently skip the fetching if so (I am guessing this is what `cargo` does, since it works fine offline as long as you have the right deps). This will keep the  build system UX the same as it was before, while also fixing the update problem.

2022-09-12 22:26 UTC, gregnazario commented
> I'm wondering whether we have any examples of other language frameworks where things are automatically updated with each build. Does cargo does this? Not sure but I think not.
> 
> Best practice IMO should be to always use a static github reference (commit hash or stable branch).

I know that cargo does download a new one if you change it, but I'm unsure of whether you use a branch if it is.

Realistically, if you want a stable change you should use a git rev correct?

2022-09-13 01:55 UTC, sblackshear commented
>  Does cargo does this? Not sure but I think not.

Cargo does do this if you use a git dep on repo w/o specified rev or on a branch instead of a specific commit.

> Best practice IMO should be to always use a static github reference (commit hash or stable branch).

I wholeheartedly agree with this as best practices + the common case. But I do think there are use-cases for auto-updates, especially in the early days of a network. As one concrete example: applications depending on the Sui or Aptos Framework code. Projects do not have any agency over which version of the Framework they use--they have to go with whatever is published on-chain. E.g., in Sui right now, we recommend that Move projects use a git dep on our `devnet` branch, which gets updated once/week. Asking folks to change their Move.toml's every time we upgrade the devnet would be cumbersome, particularly because they have no choice but to use the newest version if they want their code to work on devnet.

2022-09-13 04:13 UTC, gregnazario commented
> > Does cargo does this? Not sure but I think not.
> 
> Cargo does do this if you use a git dep on repo w/o specified rev or on a branch instead of a specific commit.
> 
> > Best practice IMO should be to always use a static github reference (commit hash or stable branch).
> 
> I wholeheartedly agree with this as best practices + the common case. But I do think there are use-cases for auto-updates, especially in the early days of a network. As one concrete example: applications depending on the Sui or Aptos Framework code. Projects do not have any agency over which version of the Framework they use--they have to go with whatever is published on-chain. E.g., in Sui right now, we recommend that Move projects use a git dep on our `devnet` branch, which gets updated once/week. Asking folks to change their Move.toml's every time we upgrade the devnet would be cumbersome, particularly because they have no choice but to use the newest version if they want their code to work on devnet.

This is the exact case that I'm trying to fix.  Similarly people use the branch, and it gets stuck in time.  We then tell people they have to clean, and then redownload the whole git repos, which is a lot more cumbersome, as it uses a large overhead in networking.

Instead by updating the in place one, we take advantage of what git does best, incremental updates.

2022-09-13 04:19 UTC, wrwg commented
> > > Does cargo does this? Not sure but I think not.
> > 
> > 
> > Cargo does do this if you use a git dep on repo w/o specified rev or on a branch instead of a specific commit.
> > > Best practice IMO should be to always use a static github reference (commit hash or stable branch).
> > 
> > 
> > I wholeheartedly agree with this as best practices + the common case. But I do think there are use-cases for auto-updates, especially in the early days of a network. As one concrete example: applications depending on the Sui or Aptos Framework code. Projects do not have any agency over which version of the Framework they use--they have to go with whatever is published on-chain. E.g., in Sui right now, we recommend that Move projects use a git dep on our `devnet` branch, which gets updated once/week. Asking folks to change their Move.toml's every time we upgrade the devnet would be cumbersome, particularly because they have no choice but to use the newest version if they want their code to work on devnet.
> 
> This is the exact case that I'm trying to fix. Similarly people use the branch, and it gets stuck in time. We then tell people they have to clean, and then redownload the whole git repos, which is a lot more cumbersome, as it uses a large overhead in networking.
> 
> Instead by updating the in place one, we take advantage of what git does best, incremental updates.

Fine then with this as a general feature! I did not know about the cargo behavior here. How we use it in aptos should be a separate discussion.

2022-09-13 04:19 UTC, wrwg approved these changes

2022-09-13 04:25 UTC, gregnazario commented
@sblackshear I addressed your comments

2022-09-13 04:26 UTC, sblackshear approved these changes
Thanks for adding the option!

2022-09-25 20:16 UTC, gregnazario commented
Looks like some test was doing something wonky with opt out.  So, I've changed it to opt in (by default it doesn't fetch latest dependencies)

2022-09-25 20:50 UTC, merged