[compatibility] Relax compatibility for friends
move-language/move pull request #479
Opened 2022-09-13 20:52 UTC by wrwg

This adds a cargo feature flag which if set, lets the compatibility check treat friend functions like private functions. The feature is not on by default because it assumes that modules are compiled and published on package granularity level. On package level, we can assume that each call site of the friend function has been updated to the changed friend function as well.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/move-language/move/blob/main/CONTRIBUTING.md#developer-workflow)?

Yes

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

NA

2022-09-13 21:45 UTC, vgao1996 commented on language/move-binary-format/src/compatibility.rs
> +static TREAT_FRIEND_AS_PRIVATE: AtomicBool = AtomicBool::new(false);
I understand we are in a rush, but controlling this using an (effectively) mutable global variable really seems like an anti-pattern to me. Can we just pass this in as a parameter?

Notice that we already have an interface that passes in a verifier config
```
pub fn new_with_verifier_config(
        natives: impl IntoIterator<Item = (AccountAddress, Identifier, Identifier, NativeFunction)>,
        verifier_config: VerifierConfig,
    ) -> VMResult<Self> {
        Ok(Self {
            runtime: VMRuntime::new(natives, verifier_config)
                .map_err(|err| err.finish(Location::Undefined))?,
        })
    }
```
We can extend this easily by defining a VM config and change `new_with_verifier_config` to `new_with_vm_config`
```
struct MoveVMConfig {
    verifier_config: VerifierConfig,
    treat_friend_as_private: bool,
}
```

2022-09-13 21:45 UTC, vgao1996 requested changes
I understand we are in a rush, but controlling this using an (effectively) mutable and shared global variable really seems like an anti-pattern to me. Can we just pass this in as a parameter?

Notice that we already have an interface that passes in a verifier config
```
pub fn new_with_verifier_config(
        natives: impl IntoIterator<Item = (AccountAddress, Identifier, Identifier, NativeFunction)>,
        verifier_config: VerifierConfig,
    ) -> VMResult<Self> {
        Ok(Self {
            runtime: VMRuntime::new(natives, verifier_config)
                .map_err(|err| err.finish(Location::Undefined))?,
        })
    }
```
We can extend this easily by defining a VM config and change `new_with_verifier_config` to `new_with_vm_config`
```
struct MoveVMConfig {
    verifier_config: VerifierConfig,
    treat_friend_as_private: bool,
}
```

2022-09-13 23:46 UTC, sblackshear commented
I'm personally ok with making this the default behavior rather than gating it with a feature flag:

- The VM's `publish` API currently forces you to have all `friend` modules published under the same address
- Sui's publishing construct works at the package level and does not allow X-package friends (and do not plan to change this)

We should check with @jolestar to see about StarCoin's policy on this.

2022-09-14 00:13 UTC, wrwg commented
> I understand we are in a rush, but controlling this using an (effectively) mutable and shared global variable really seems like an anti-pattern to me. Can we just pass this in as a parameter?
> 
> Notice that we already have an entry point that passes in a verifier config
> 
> ```
> pub fn new_with_verifier_config(
>         natives: impl IntoIterator<Item = (AccountAddress, Identifier, Identifier, NativeFunction)>,
>         verifier_config: VerifierConfig,
>     ) -> VMResult<Self> {
>         Ok(Self {
>             runtime: VMRuntime::new(natives, verifier_config)
>                 .map_err(|err| err.finish(Location::Undefined))?,
>         })
>     }
> ```
> 
> We can extend this easily by defining a VM config and change `new_with_verifier_config` to `new_with_vm_config`
> 
> ```
> struct MoveVMConfig {
>     verifier_config: VerifierConfig,
>     treat_friend_as_private: bool,
> }
> ```
> 
> Another reason why I think we should do it this way is because we'll need other config options to control the VM's behaviors in some other ways in the future, so why not just lay down the foundation for that now.

Unfortunately, compatibility checking is not happening in the verifier, but in the VM, in `VMRuntime::publish_module_bundle`.

> I understand we are in a rush, but controlling this using an (effectively) mutable and shared global variable really seems like an anti-pattern to me. Can we just pass this in as a parameter?
> 
> Notice that we already have an entry point that passes in a verifier config
> 
> ```
> pub fn new_with_verifier_config(
>         natives: impl IntoIterator<Item = (AccountAddress, Identifier, Identifier, NativeFunction)>,
>         verifier_config: VerifierConfig,
>     ) -> VMResult<Self> {
>         Ok(Self {
>             runtime: VMRuntime::new(natives, verifier_config)
>                 .map_err(|err| err.finish(Location::Undefined))?,
>         })
>     }
> ```
> 
> We can extend this easily by defining a VM config and change `new_with_verifier_config` to `new_with_vm_config`
> 
> ```
> struct MoveVMConfig {
>     verifier_config: VerifierConfig,
>     treat_friend_as_private: bool,
> }
> ```
> 
> Another reason why I think we should do it this way is because we'll need other config options to control the VM's behaviors in some other ways in the future, so why not just lay down the foundation for that now.

Did not know we already have this config, using it now.

2022-09-14 00:14 UTC, wrwg commented
> I understand we are in a rush, but controlling this using an (effectively) mutable and shared global variable really seems like an anti-pattern to me. Can we just pass this in as a parameter?
> 
> Notice that we already have an entry point that passes in a verifier config
> 
> ```
> pub fn new_with_verifier_config(
>         natives: impl IntoIterator<Item = (AccountAddress, Identifier, Identifier, NativeFunction)>,
>         verifier_config: VerifierConfig,
>     ) -> VMResult<Self> {
>         Ok(Self {
>             runtime: VMRuntime::new(natives, verifier_config)
>                 .map_err(|err| err.finish(Location::Undefined))?,
>         })
>     }
> ```
> 
> We can extend this easily by defining a VM config and change `new_with_verifier_config` to `new_with_vm_config`
> 
> ```
> struct MoveVMConfig {
>     verifier_config: VerifierConfig,
>     treat_friend_as_private: bool,
> }
> ```
> 
> Another reason why I think we should do it this way is because we'll need other config options to control the VM's behaviors in some other ways in the future, so why not just lay down the foundation for that now.

Wonderful -- did not know we have this config already. Using it now.

2022-09-14 00:15 UTC, wrwg commented
> I'm personally ok with making this the default behavior rather than gating it with a feature flag:
> 
> * The VM's `publish` API currently forces you to have all `friend` modules published under the same address
> * Sui's publishing construct works at the package level and does not allow X-package friends (and do not plan to change this)
> 
> We should check with @jolestar to see about StarCoin's policy on this.

Unfortunately, we need the flag for downwards compatible upgrades anyway. I hope we can get rid of it the next time we reset the network.

2022-09-14 01:19 UTC, jolestar commented
> I'm personally ok with making this the default behavior rather than gating it with a feature flag:
> 
> * The VM's `publish` API currently forces you to have all `friend` modules published under the same address
> * Sui's publishing construct works at the package level and does not allow X-package friends (and do not plan to change this)
> 
> We should check with @jolestar to see about StarCoin's policy on this.

Starcoin's policy is the same. The `friend` function is only available for the same address's module so that it can be treated as private.

2022-09-14 02:15 UTC, davidiw approved these changes

2022-09-14 02:21 UTC, merged