[account-address] Input and output with a 0x for hex output
move-language/move pull request #7
Opened 2022-04-12 22:57 UTC by gregnazario

### Summary

Accepts 0x as an input, and will print the output as a 0x for AccountAddress.
This removes confusion on whether it's in a different encoding, and keeps
it simple.

### Motivation

Addresses should start with a `0x` as I have been described by Todd how a hex literal must have `0x` in front of it.  Otherwise, we're being inconsistent and having `0x` in code, but no `0x` outside of it for the same representation.

Updated version from: https://github.com/diem/move/pull/199

2022-04-13 14:31 UTC, wrwg requested changes
Can you please please rebase and push again? The rust toolchain was upgraded and I'm concerned we merge this as this, new linter errors will slip in, as the new toolchain is more  pedantic.

2022-04-13 15:15 UTC, gregnazario commented
> Can you please please rebase and push again? The rust toolchain was upgraded and I'm concerned we merge this as this, new linter errors will slip in, as the new toolchain is more pedantic.

@wrwg I've rebased it in

2022-04-13 15:28 UTC, gregnazario commented
Turns out I had a test in a rust block in a comment.  I created a new task to track these kinds of issues https://github.com/aptos-labs/aptos-core/issues/503

/land

2022-04-13 15:39 UTC, wrwg commented
Adding @tnowacki which I think reviewed this PR in the old repo.

2022-04-13 17:33 UTC, gregnazario commented
> I think its totally reasonable to require `0x` if you aren't using the source language, where it is a bit more obvious what is going on (I hope).

Yeah, it's mostly about the output from the Rust attached code e.g. if I print the address, it should print out in a way that I can copy it and put it into move code the same way, so that's why I decided to make this match the hex literal.  Everything should be consistent on the hex output, and then you can simply copy paste from one place to another, without thinking about whether you need to add 0x or not.

> Do you know if this code affects the package system? We had an open issue for that

I'm not aware if it affects the package system.  Is there a test for that?

2022-04-13 18:12 UTC, tnowacki commented
> I'm not aware if it affects the package system. Is there a test for that?

Would you mind adding a quick one? :D It should be fairly easy

If you look at `language/tools/move-package/tests/test_sources/parsing/invalid_hex_address_in_subst` as an example, you could just copy this and do `language/tools/move-package/tests/test_sources/parsing/invalid_non_hex_address` with  a `Move.toml` that looks like 

```
[package]
name = "name"
version = "0.1.2"

[addresses]
A = "1234"
```

It doesn't need to be fixed for this PR, just we should maybe test if it is also fixed, would be a fun bonus :)

2022-04-14 16:23 UTC, gregnazario commented
> > I'm not aware if it affects the package system. Is there a test for that?
> 
> Would you mind adding a quick one? :D It should be fairly easy
> 
> If you look at `language/tools/move-package/tests/test_sources/parsing/invalid_hex_address_in_subst` as an example, you could just copy this and do `language/tools/move-package/tests/test_sources/parsing/invalid_non_hex_address` with a `Move.toml` that looks like
> 
> ```
> [package]
> name = "name"
> version = "0.1.2"
> 
> [addresses]
> A = "1234"
> ```
> 
> It doesn't need to be fixed for this PR, just we should maybe test if it is also fixed, would be a fun bonus :)

I'm not sure what's supposed to be in the `.exp` file, is it supposed to be the error that's thrown?

2022-04-14 17:44 UTC, tnowacki commented
> I'm not sure what's supposed to be in the .exp file, is it supposed to be the error that's thrown?

If your change affects the package system, there will be an error. If it does not, there shouldn't be one. (but we probably want this to be an error)
You can double check this by running the test on main and again on your branch.

You can run the test by `cargo test -p move-package`.
You can create the `.exp` file once you think the output is correct with `UB=1  cargo test -p move-package` which will update the `.exp` files for all tests.

2022-04-14 17:51 UTC, gregnazario commented
@tnowacki I added the test as expected :)

2022-04-14 20:23 UTC, davidiw approved these changes
let's get the linter issues fixed and get this landed.

2022-04-14 21:36 UTC, gregnazario commented
/land (maybe?)

2022-04-14 21:36 UTC, merged